version: '2'

services:
  kopay_server_staging:
    container_name: kopay_server_staging
    build: 
      context: ./server
      dockerfile: production.dockerfile
    env_file: ./server/env/staging
    ports:
     - 4005:4005
    expose: 
     - 4005
    links:
     - "mongodb_staging:mongodb_staging"
    volumes:
     - "./server:/app"
    working_dir: /app
    depends_on:
     - mongodb_staging
    networks:
     - kopay_staging_nw     
      
  kopay_client_staging:
    container_name: kopay_client_staging
    build: 
      context: ./client
      dockerfile: production.dockerfile
    env_file: ./client/env/staging
    volumes:
     - "./client:/app"
    expose:
     - 4000
    working_dir: /app
    depends_on:
     - kopay_server_staging
     - ghost_staging
    networks:
     - kopay_staging_nw

  ghost_staging:
    image: ghost:1-alpine
    container_name: ghost_staging
    env_file: ./ghost/env/staging
    volumes:
      - ./ghost:/var/lib/ghost/content
    ports:
      - 127.0.0.1:2468:2368
    expose:
      - 2368
    networks: 
      - kopay_staging_nw

  mongodb_staging:
    container_name: mongodb_staging
    image: mongo
    build: 
      context: .
      dockerfile: ./mongo/production.dockerfile
    ports:
     - 127.0.0.1:27037:27037
    expose:
     - 27037
    volumes:
     - "/usr/local/mongodb/staging:/data/db"
    env_file: ./mongo/env/staging
    networks:
     - kopay_staging_nw

networks:
  kopay_staging_nw:
    driver: bridge