export default {
    ADMIN_ORDERS_TABLE: 'ADMIN_ORDERS_TABLE',
    CUSTOMER_ORDERS_TABLE: 'CUSTOMER_ORDERS_TABLE',
    PRODUCTS_INDEX_GRID: 'PRODUCTS_INDEX_GRID',
    ADMIN_PRODUCTS: 'ADMIN_PRODUCTS',
    ADMIN_PACKAGES_MODAL_ALL_PRODUCTS: 'ADMIN_PACKAGES_MODAL_ALL_PRODUCTS',
    ADMIN_PACKAGES_MODAL_PACKAGE_ITEMS: 'ADMIN_PACKAGES_MODAL_PACKAGE_ITEMS',
    ADMIN_PACKAGES: 'ADMIN_PACKAGES',
    ADMIN_PRODUCT_GROUPS: 'ADMIN_PRODUCT_GROUPS',
    ADMIN_PRODUCT_GROUP_MODAL_OWN_PRODUCTS: 'ADMIN_PRODUCT_GROUP_MODAL_OWN_PRODUCTS',
    ADMIN_PRODUCT_GROUP_MODAL_OWN_ALL_PRODUCTS: 'ADMIN_PRODUCT_GROUP_MODAL_OWN_ALL_PRODUCTS',
    ADMIN_PRODUCT_GROUP_MODAL_ALL_PRODUCTS: 'ADMIN_PRODUCT_GROUP_MODAL_ALL_PRODUCTS',
    ADMIN_DISCOUNTS: 'ADMIN_DISCOUNTS'
};