export default {
    PRODUCT_GROUP: 'PRODUCT_GROUP',
    DISCOUNT: 'DISCOUNT',
    DISPLAY_ITEM: 'DISPLAY_ITEM',
    ADMIN_PACKAGE: 'ADMIN_PACKAGE',
    ADMIN_ORDER: 'ADMIN_ORDER',
    CUSTOMER_ORDER: 'CUSTOMER_ORDER',
    APP_SETTINGS: 'APP_SETTINGS'
};